# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint      # Check error wrapping (Go 1.13+)
    - gosec          # Security linter
    - copyloopvar    # Detect loop variable copying issues
    - goconst        # Find repeated strings that could be constants
    - misspell       # Find common typos
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    staticcheck:
      checks: ["all"]
    gosec:
      # Exclude G204 (subprocess launched with variable) - we intentionally use variables for tool paths
      excludes:
        - G204
    goconst:
      min-len: 3
      min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  relative-path-mode: wd
